services:
  flask:
    build:
      dockerfile: ./docker/Dockerfile_prod
    expose:
      - 8001
    environment:
      - LOG_TO_FILE=1
    volumes:
      - ../arktools-volumes/logs/gunicorn:/var/log/gunicorn

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    links:
      - flask
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - ../arktools-volumes/certbot/conf:/etc/letsencrypt
      - ../arktools-volumes/certbot/www:/var/www/certbot
      - ../arktools-volumes/logs/nginx:/var/log/nginx
  certbot:
    image: certbot/certbot
    volumes:
      - ../arktools-volumes/certbot/conf:/etc/letsencrypt
      - ../arktools-volumes/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"