"""ark

Revision ID: 6f06474bb842
Revises: faeb4653000f
Create Date: 2023-09-20 09:51:38.904783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f06474bb842'
down_revision = 'faeb4653000f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ark', sa.Column('shoulder', sa.String(length=20), nullable=True))
    op.add_column('ark', sa.Column('url', sa.String(length=1000), nullable=True))
    op.create_foreign_key(None, 'ark', 'shoulder', ['shoulder'], ['shoulder'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ark', type_='foreignkey')
    op.drop_column('ark', 'url')
    op.drop_column('ark', 'shoulder')
    # ### end Alembic commands ###
