"""init

Revision ID: faeb4653000f
Revises: 
Create Date: 2023-09-20 09:16:06.304606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faeb4653000f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('naan',
    sa.Column('naan', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('naan')
    )
    op.create_table('ark',
    sa.Column('identifier', sa.String(length=100), autoincrement=False, nullable=False),
    sa.Column('naan', sa.Integer(), nullable=True),
    sa.Column('assigned_name', sa.String(length=1000), nullable=True),
    sa.Column('who', sa.String(length=500), nullable=True),
    sa.Column('what', sa.String(length=500), nullable=True),
    sa.Column('when', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['naan'], ['naan.naan'], ),
    sa.PrimaryKeyConstraint('identifier')
    )
    op.create_table('shoulder',
    sa.Column('shoulder', sa.String(length=50), autoincrement=False, nullable=False),
    sa.Column('naan', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['naan'], ['naan.naan'], ),
    sa.PrimaryKeyConstraint('shoulder')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shoulder')
    op.drop_table('ark')
    op.drop_table('naan')
    # ### end Alembic commands ###
