ARG PYTHON_VERSION
ARG DEBIAN_RELEASE

FROM python:${PYTHON_VERSION}-slim-${DEBIAN_RELEASE} AS builder

RUN apt-get update \
  && apt-get install -y build-essential \
  && apt-get purge -y --auto-remove \
  && rm -fr /var/lib/apt/lists/*

WORKDIR /code

ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

COPY requirements requirements
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements/prod.txt

#ENTRYPOINT ["python"]
#CMD ["app.py"]

#COPY ./docker/entrypoint /srv/entrypoint
#RUN sed -i 's/\r$//g' /srv/entrypoint
#RUN chmod +x /srv/entrypoint

#COPY ./docker/start /srv/start
#RUN sed -i 's/\r$//g' /srv/start
#RUN chmod +x /srv/start

ENV FLASK_APP=wsgi.py
ENV FLASK_DEBUG=0
ENV FLASK_ENV=production

# Create log directory for gunicorn access logs
RUN mkdir -p /var/log/gunicorn

COPY gunicorn_conf.py /code/gunicorn_conf.py

ENTRYPOINT ["gunicorn", "-c", "gunicorn_conf.py", "wsgi:app"]